# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://djcurill.github.io/explore/"

git_url = "https://github.com/djcurill/explore/tree/master/"

def custom_doc_links(name): return None
